FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
# Usuń stały port - Render ustawi zmienną PORT
ENV ASPNETCORE_URLS=http://+:${PORT:-8080}
EXPOSE 8080
RUN mkdir -p /app/wwwroot/images/locations \
    && chown -R 1000:1000 /app/wwwroot/images

USER 1000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Guessnica-backend/Guessnica-backend.csproj", "Guessnica-backend/"]
RUN dotnet restore "Guessnica-backend/Guessnica-backend.csproj"
COPY . .
WORKDIR "/src/Guessnica-backend"
RUN dotnet build "./Guessnica-backend.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Guessnica-backend.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Guessnica-backend.dll"]